### ISSUE TITLE
Sound // ADD!

### ISSUE THREAD

**Issue by Lazerplayz** [NetherGamesMCPE/RapCobra#12]
https://github.com/pmmp/PocketMine-MP/commit/0535acf211f9f306a610307f71b29349b5e156d2

This commit has added sound to mcpe we need this!

**Comment by keithkfng** [comment]
I don't think it exactly added sound...

**Comment by Lazerplayz** [comment]
It has I have tested it

**Comment by keithkfng** [comment]
On what? You can't add the code itself into the phar -_-

**Comment by Lazerplayz** [comment]
? I've tested that pocketmine-mp edit it works fine geez
